/**
 * Created by ermo4enkov on 3/7/17.
 */


try {
    console.log("All cool");
    llalla;
} catch (ex) {
    console.log(ex);
}

// в ex передастся причина выброса ошибки